export const CompanyName = 'Indus Car Mart'
export const HomeTab = 'Home'
export const Search = 'Search'
export const Model = 'Model'
export const Year = 'Year'
export const CartTab = 'Cart'
export const MessagesTab = 'Messages'